### ISSUE TITLE
crontab entry must end with a newline

### ISSUE THREAD

**Issue by David-at-TechCXO** [bitnami/bncert#1]
```
Error: Error running crontab -u bitnami /tmp/cron20221129011251: new crontab file is missing newline before EOF, can't install.
```

**Comment by marcosbc** [comment]
Hi @David-at-TechCXO, it seems like this error could happen if the previous crontab file was already invalid.

Could you execute the following command to understand what the tool is seeing?

```
$ sudo crontab -u bitnami -l
```
