### ISSUE TITLE
Download do not work anymore

### ISSUE THREAD

**Issue by StfBauer** [bitnami/bncert#12]
### What steps will reproduce the bug?

Download

wget -O bncert-linux-x64.run https://downloads.bitnami.com/files/bncert/latest/bncert-linux-x64.run

### What is the expected behavior?

Download bncert but instead just download a HTML file.

### What do you see instead?

```html
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="refresh" content="1;url=https://bitnami.com">
        <script type="text/javascript">
            window.location.href = "https://bitnami.com";
        </script>
        <title>Page Redirection</title>
    </head>
    <body>
        If you are not redirected automatically, follow the <a href='https://bitnami.com'>link</
a>
    </body>
</html>
```

**Comment by gustavovalverde** [comment]
This also causes people upgrading recently to make their executable to start failing, as it's actually trying to run this HTML, so this will break existing stable installations.

**Comment by beltran-rubo** [comment]
Thanks for reporting it, there was an issue with CloudFront and we are working on enabling back again the link.

**Comment by beltran-rubo** [comment]
It is now available again, sorry for the inconvenience.
