### ISSUE TITLE
Cronjob fails to update certificate if there is an update to bncert

### ISSUE THREAD

**Issue by CMeldgaard** [bitnami/bncert#5]
### What steps will reproduce the bug?

When the cronjob that bncert creates runs an update of a certificate it will fail if there is an update to the bncert tool.

Is there some command we can run along with the cronjob, that only updates the bncert tool, but doesn't run an update of the certificates?

### What do you see instead?

-

**Comment by marcosbc** [comment]
Hi @CMeldgaard, AFAIK bncert does not execute with the cron job that gets created by the tool. Here can you see the related logic: https://github.com/bitnami/bncert/blob/main/project/bncert-letsencrypt-functions.xml#L305

**Comment by CMeldgaard** [comment]
@marcosbc What happens when i run bncert and there is a update ? Does it just run a update of lego ?

**Comment by marcosbc** [comment]
If you run a complete execution of Bncert (to create a new cert or renew an existing one), it will upgrade Lego if the installation's one is outdated, as well as replacing the cron line with a different timestamp.

But as far as the cron job goes, Bncert is not executed here and therefore nothing will be upgraded: Only the Lego tool is called.

**Comment by marcosbc** [comment]
Since there haven't been any updates to this issue for a few weeks, I'm proceeding to close it.
