### ISSUE TITLE
The path does not seem to contain a valid Bitnami installation using bitnami/phpbb container.

### ISSUE THREAD

**Issue by EneasVVA** [bitnami/bncert#6]
### What steps will reproduce the bug?

I am using the phpBB container provided by Bitnami. Despite the documentation directing me to use the bncert-tool, this tool is unable to recognize the Bitnami installation which seems to be in its default location at /opt/bitnami. Moreover, I have attempted to use several alternative paths with no success.

I am seeking assistance to understand why the tool cannot locate the installation and how I might go about resolving this issue. It is crucial that the documentation aligns with the actual functionality of the tool to prevent such issues in the future.

### What is the expected behavior?

----------------------------------------------------------------------------
Welcome to the Bitnami HTTPS Configuration tool.

----------------------------------------------------------------------------
Bitnami installation directory

Please type a directory that contains a Bitnami installation. The default
installation directory for Linux installers is a directory inside /opt.

Bitnami installation directory []: /opt/bitnami

Warning: The path does not seem to contain a valid Bitnami installation. Make
sure you have proper access rights, or choose a different directory.
Press [Enter] to continue:
----------------------------------------------------------------------------

### What do you see instead?

It should be specified somewhere which files it is looking for and/or there should be a flexible way to adjust the paths.

**Comment by gongomgra** [comment]
Hi @EneasVVA,

Thanks for using Bitnami, and sorry for the delay on getting back to you. The bncert tool is not meant to be used in our containers, only in our cloud images and virtual-machines solutions. In your case, the tool is looking for some files not present in containers solutions, which ends up returning that "Bitnami installation not found" message.

As an alternative, you can manually install and run the Let's Encrypt binary (`lego` tool) as described in the guide linked below

https://docs.bitnami.com/aws/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

Hope it helps!
